# This file was generated by GoReleaser. DO NOT EDIT.
cask "zing" do
  name "zing"
  desc "Zing helps developers zing through repetitive commands."
  homepage "https://github.com/chuksgpfr/zing"
  version "0.0.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zing"

  on_macos do
    on_intel do
      url "https://github.com/chuksgpfr/zing/releases/download/v#{version}/zing_#{version}_darwin_amd64.tar.gz"
      sha256 "cf88ce68e9a2536ded503f243006ad3b0b0bb1be48f8a6795570a75a5126cc9a"
    end
    on_arm do
      url "https://github.com/chuksgpfr/zing/releases/download/v#{version}/zing_#{version}_darwin_arm64.tar.gz"
      sha256 "771c5bc2dd5a07f451ea7cb5dbd5402bc64942a1ccc70c55a86b199a487b767b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chuksgpfr/zing/releases/download/v#{version}/zing_#{version}_linux_amd64.tar.gz"
      sha256 "0d58de314b95a2c51142b081472beb536d205e8ea2caa75bd803a663539f41c9"
    end
    on_arm do
      url "https://github.com/chuksgpfr/zing/releases/download/v#{version}/zing_#{version}_linux_arm64.tar.gz"
      sha256 "c5a1b4e4d015cfeb0e9f01a45653e1aabf0302544f5cb99612d411b1033cd3ac"
    end
  end

  # No zap stanza required
end
